/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AButton: (typeof import('ant-design-vue/es'))['Button'];
  const ACard: (typeof import('ant-design-vue/es'))['Card'];
  const AEmpty: (typeof import('ant-design-vue/es'))['Empty'];
  const AInput: (typeof import('ant-design-vue/es'))['Input'];
  const ASelect: (typeof import('ant-design-vue/es'))['Select'];
  const ATable: (typeof import('ant-design-vue/es'))['Table'];
  const ATag: (typeof import('ant-design-vue/es'))['Tag'];
  const ATextarea: (typeof import('ant-design-vue/es'))['Textarea'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
}
